playerNum	=	2
wallNum	    =	3
winHeight	=	400
winWidth	=	600
wallThick	=	4
pWidth		=	32			;人物图片的宽度
pHeight		=	32
dieWidth	=   112
dieHeight   =   74

playerWidth equ  20          ;实际人物的宽度，用于碰撞检测
pPos		equ	150			;人物右下角的x坐标
PEOPLE_1	equ 101
PEOPLE_2	equ	65535
PEOPLE_3    equ 104
ID_Timer	equ 1	
DIE_1       equ 105
DIE_2       equ 106
DIE_3       equ 107
DIE_4       equ 108
GAME_OVER	equ	115
MAIN_MENU   equ 2
FREQUENCY   equ 40
TIMERID		equ 123
HELP		equ	112
;------------------------
wallMaxHeight = 40
moveSpeed	  =  6 
wallSafeDistance   = 150 
wallGenerateChance = 23
personJumpSpeed  =  20
accelerateSpeed  =  2
